### ISSUE TITLE
Error when loading 3 titles on 8MByte card

### ISSUE THREAD

**Issue by Eloeri** [retrostage/SNES_Multicart_Maker#1]
When trying to load 3 games, total size 8MByte after the expansion of the 512Kbyte games
<img width="522" alt="image" src="https://user-images.githubusercontent.com/42394653/144728879-f955bf27-c0cf-40ed-bf35-320bfa5f4876.png">
This error pops up: 
![image](https://user-images.githubusercontent.com/42394653/144728887-94920306-4d4c-48d0-91b9-cfa24ef42fe6.png)

Any suggestions?

**Comment by retrostage** [comment]
It's exactly as the error states. You're loading 3 games, which is fine, but one of your games is 4MByte. That won't work, so the error comes up. For more than 2 games, 2MByte is the max size for each game (on a 8MByte board).

Specifically, the 8MByte Blaster can handle 2x 4MByte games, or up to 4 games that are 2MByte or less. The 16MByte Blaster will do up to 4 games, each game slot has a max 4MByte size.

**Comment by Eloeri** [comment]
Ah, gotcha. Thought I was good even though I was under the total cart size. Thanks again!

**Comment by retrostage** [comment]
Yeah it's just due to bank sizes and how the multi-cart handles switching
banks when a reset happens.
