### ISSUE TITLE
"Unhandled Exception" loading two 3MByte games

### ISSUE THREAD

**Issue by Eloeri** [retrostage/SNES_Multicart_Maker#2]
When trying to load Earthworm Jim 1 & 2:
![image](https://user-images.githubusercontent.com/42394653/144947787-92243979-dc71-4262-bc2d-291547d7933a.png)
![image](https://user-images.githubusercontent.com/42394653/144947794-89b4ed11-8de1-48b2-beda-877aedfca8f6.png)
An "unhandled exception" error pops up.
![image](https://user-images.githubusercontent.com/42394653/144947839-93448652-f038-451c-9601-9805e8a3c4c1.png)

**Comment by retrostage** [comment]
Checking into it now.

**Comment by retrostage** [comment]
Should be fixed in v0.02 release, just uploaded.
