### ISSUE TITLE
Can't build 2 game multicart

### ISSUE THREAD

**Issue by BLINXERIZER** [retrostage/SNES_Multicart_Maker#3]
I'm trying to do a multicart of both Pocky & Rocky 1 & 2. 

P&R 1 is 1MB and P&R 2 is 1.5MB but the program gives me the error in the attached picture.

Neither one use SRAM and are both under 2MB. I'm also using no intro ROMs

![SNES multicart error](https://user-images.githubusercontent.com/108152916/179859315-63286b41-070a-4130-918d-d31d4a0990e1.jpg)

**Comment by retrostage** [comment]
This should be fixed now in v0.03, available in the Releases section now.
